export const bookList = [
  {
    id: 1,
    image: "../../images/cal.jpg",
    title: "Math-Calculus 1",
    author: "Mostafa Hassan",
    publishDate: "January 1, 2022",
    price: "$20.99",
  },
  {
    id: 2,
    image: "../../images/call.jpg",
    title: "Math-Calculus 2",
    author: "Mostafa Hassan",
    publishDate: "February 15, 2023",
    price: "$15.99",
  },
  {
    id: 3,
    image: "../../images/chem.jpg",
    title: "Chemistry I",
    author: "Mostafa Hassan",
    publishDate: "March 10, 2021",
    price: "$12.99",
  },
  {
    id: 4,
    image: "../../images/dat.jpg",
    title: "Advanced Database",
    author: "Mostafa Hassan",
    publishDate: "April 5, 2020",
    price: "$18.99",
  },
  {
    id: 5,
    image: "../../images/ob.jpeg",
    title: "Object Oriented Software engineering",
    author: "Mostafa Hassan",
    publishDate: "May 20, 2019",
    price: "$24.99",
  },
  {
    id: 6,
    image: "../../images/mac.jpg",
    title: "Machine Learning",
    author: "Mostafa Hassan",
    publishDate: "June 12, 2022",
    price: "$14.99",
  },
];